db {
  type : "mysql"
  user : "root"
  password : "root"
  host : "127.0.0.1:3306"
  database : "caddyui"
  prefix : ""
  debug : true
}
log {
  debug : false
  colorable : false
  saveFile : ""
  fileMaxBytes : 0
  targets : "console"
}
sys {
  accounts : {
    admin : "admin"
  }
  sslHosts : []
  sslCertFile : ""
  sslKeyFile : ""
  debug : true
}
cookie {
  path     : "/"
  domain   : ""
  maxAge   : 0
  httpOnly : true
  hashKey  : "123456789012345678901234567890aa" #32位
  blockKey : "123456789012345678901234567890cc" #32位
}
ftp {
  pidFile        : ""
  ###########暂时无效################
	#dbType         : ""
	#ftpStoreType   : ""
	#ftpOptions     : ""
  ###########################
  name           : ""
  hostName       : ""
  publicIP       : ""
  passivePorts   : ""
  port           : 233
	tls            : false
	certFile       : ""
  keyFile        : ""
	explicitFTPS   : false
	welcomeMessage : ""
}