db {
  type : "mysql"
  user : "root"
  password : "root"
  host : "127.0.0.1:3306"
  database : "nging"
  prefix : ""
  debug : true
}
log {
  debug : false
  colorable : false
  saveFile : ""
  fileMaxBytes : 0
  targets : "console"
}
sys {
  vhostsfileDir : "config/vhosts"
  allowIP : []
  sslHosts : []
  sslCacheDir : ""
  sslKeyFile : ""
  sslCertFile : ""
  debug : true
  editableFileExtensions {
    bat : "bat"
    css : "css"
    go : "golang"
    htm : "html"
    html : "html"
    ini : "ini"
    js : "javascript"
    markdown : "markdown"
    md : "markdown"
    php : "php"
    pl : "pl"
    sh : "sh"
    sql : "sql"
    txt : "txt"
    xml : "xml"
    yaml : "yaml"
    yml : "yaml"
  }
  editableFileMaxSize : "1M"
  editableFileMaxBytes : 1048576
  errorPages {
    0 : "error/other"
    404 : "error/404"
    500 : "error/500"
  }
  cmdTimeout : ""
}
email {
  Username : "swh@admpub.com"
  Password : ""
  Host : "smtp.exmail.qq.com"
  Port : 465
  Secure : "SSL"
  Identity : ""
  Timeout : 0
  Engine : ""
  From : "swh@admpub.com"
  QueueSize : 10
}
cron {
  poolSize : 100
  template : ""
}
cookie {
  domain : ""
  maxAge : 0
  path : "/"
  httpOnly : true
  hashKey : "123456789012345678901234567890aa"
  blockKey : "123456789012345678901234567890cc"
}
caddy {
  agreed : false
  caURL : "https://acme-v01.api.letsencrypt.org/directory"
  caddyFile : "./Caddyfile"
  cpu : "100%"
  caEmail : ""
  caTimeout : 10
  logFile : ""
  pidFile : "./caddy.pid"
  quiet : false
  revoke : ""
  serverType : "http"
  plugins : false
  version : false
}
ftp {
  pidFile : "ftp.pid"
  dbType : "mysql"
  ftpStoreType : "file"
  name : "TinyFTP"
  hostName : ""
  publicIP : "127.0.0.1"
  passivePorts : "6001-7000"
  port : 233
  tls : false
  certFile : ""
  keyFile : ""
  explicitFTPS : false
  welcomeMessage : "Welcome to the TinyFTP"
}
language {
  Default : "zh-cn"
  Fallback : ""
  AllList : ["zh-cn", "en"]
  RulesPath : ["config/i18n/rules"]
  MessagesPath : ["config/i18n/messages"]
  Reload : true
}
download {
  savePath : ""
}
