db {
  type : ""
  user : ""
  password : ""
  host : ""
  database : ""
  prefix : ""
  debug : false
}
log {
  debug : false
  colorable : false
  saveFile : ""
  fileMaxBytes : 0
  targets : "console"
}
sys {
  accounts : {
    admin : "admin"
  }
}
cookie {
  path     : "/"
  domain   : ""
  maxAge   : 0
  httpOnly : true
  hashKey  : "123456789012345678901234567890aa" #32位
  blockKey : "123456789012345678901234567890cc" #32位
}