db {
  type : "mysql"
  user : "root"
  password : "root"
  host : "127.0.0.1:3306"
  database : "caddyui"
  prefix : ""
  debug : false
}
log {
  debug : false
  colorable : false
  saveFile : ""
  fileMaxBytes : 0
  targets : "console"
}
sys {
  accounts : {
    admin : "admin"
  }
  sslHosts : []
  sslCertFile : ""
  sslKeyFile : ""
}
cookie {
  path     : "/"
  domain   : ""
  maxAge   : 0
  httpOnly : true
  hashKey  : "123456789012345678901234567890aa" #32位
  blockKey : "123456789012345678901234567890cc" #32位
}